apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stage-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@basicproject.dev
    privateKeySecretRef:
      name: stage-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx